name: Deploy to test environment on push

on:
  push:
    branches: tst

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: [self-hosted, Windows, X64, tst]
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
  test:
    needs: build
    runs-on: [self-hosted, Windows, X64, tst]
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
   
  deploy:
    needs: test
    runs-on: [self-hosted, Windows, X64, tst]
    steps:
    - name: Stop website
      shell: powershell
      run: |
        if ((Get-WebSiteState -Name FT-API).Value -eq "Started")
        {
          Stop-WebSite -Name FT-API
          echo "Stopped Website FT-API"
        }
        if ((Get-WebAppPoolState -Name FT-API).Value -eq "Started")
        {
          Stop-WebAppPool -Name FT-API
          echo "Stopped Application Pool FT-API"
        }
        Start-Sleep -s 15
    - name: Publish Release
      run: dotnet publish API --configuration Release -o C:\inetpub\wwwroot\ft-api
    - name: Start Website
      shell: powershell
      run: |
        if ((Get-WebSiteState -Name FT-API).Value -eq "Stopped")
        {
          Start-WebSite -Name FT-API
          echo "Started Website FT-API"
        }
        if ((Get-WebAppPoolState -Name FT-API).Value -eq "Stopped")
        {
          Start-WebAppPool -Name FT-API
          echo "Started Application Pool FT"
        }
